# Generated by Django 5.2.5 on 2025-09-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='creado_el',
        ),
        migrations.AddField(
            model_name='equipo',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
