# Generated by Django 5.2.5 on 2025-09-09 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_solicitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='usuario',
        ),
    ]
