# Generated by Django 5.2.5 on 2025-10-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='disponible',
        ),
        migrations.AddField(
            model_name='equipo',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
