# Generated by Django 5.2.5 on 2025-10-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_equipo_disponible_equipo_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='descripcion',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='descripcion',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
