# Generated by Django 5.2.5 on 2025-10-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_solicitud_usuario_alter_equipo_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.CharField(max_length=500)),
                ('responsable', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='equipo',
            name='descripcion',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
