# Generated by Django 5.2.5 on 2025-11-09 08:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_equipo_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mantencion',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mantenciones', to='app.equipo'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mantencion',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenciones_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('PANOLERO', 'Pañolero'), ('PROFESOR', 'Profesor'), ('ESTUDIANTE', 'Estudiante')], default='ESTUDIANTE', max_length=10)),
                ('rut', models.CharField(blank=True, max_length=12, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion_estimada', models.DateTimeField()),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('cantidad_prestada', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='app.equipo')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='app.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposito', models.CharField(max_length=200)),
                ('inicio_reserva', models.DateTimeField()),
                ('fin_reserva', models.DateTimeField()),
                ('cantidad_alumnos', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_taller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaTallerEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipo')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reservataller')),
            ],
            options={
                'unique_together': {('reserva', 'equipo')},
            },
        ),
        migrations.AddField(
            model_name='reservataller',
            name='equipos',
            field=models.ManyToManyField(related_name='reservas_taller', through='app.ReservaTallerEquipo', to='app.equipo'),
        ),
    ]
